services:
  postgreSql:
    image: postgres:latest
    container_name: postgreSql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./script/db-init/postgres:/docker-entrypoint-initdb.d
    restart: always
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgreSql:5432/${POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      - postgreSql

  mongoDb:
    image: mongo:4.4.18
    container_name: mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      TZ: Asia/Tokyo
    volumes:
      - ./data/mongodb:/data/db
      - ./script/db-init/mongo:/docker-entrypoint-initdb.d
    ports: ["27017:27017"]
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  jojihouse-system:
    build:
      context: ./jojihouse-system
      dockerfile: Dockerfile.air
    container_name: jojihouse-system
    ports:
      - "8080:8080"
    depends_on:
      postgreSql:
        condition: service_healthy
      mongoDb:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgreSql
      - POSTGRES_PORT=5432

      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
      - MONGO_HOST=mongoDb
      - MONGO_PORT=27017

      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME}
      - WEBHOOK_AVATAR_URL=${WEBHOOK_AVATAR_URL}

      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    volumes:
      - ./jojihouse-system:/go/src
    restart: always

  web:
    image: httpd:latest
    container_name: jojihouse-web
    depends_on:
      - jojihouse-system
    ports:
      - "1024:80"
    volumes:
      - "../jojihouse-system-web:/usr/local/apache2/htdocs"
