// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/entrance": {
            "post": {
                "description": "ユーザーの入室または退室を記録します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "エントランス(入退室)管理"
                ],
                "summary": "入退室記録",
                "parameters": [
                    {
                        "description": "入退室データ",
                        "name": "entrance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Entrance"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EntranceResponse"
                        }
                    }
                }
            }
        },
        "/entrance/current": {
            "get": {
                "description": "現在ハウス内にいるユーザーの一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "エントランス(入退室)管理"
                ],
                "summary": "在室ユーザー取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.UserResponse"
                            }
                        }
                    }
                }
            }
        },
        "/entrance/logs": {
            "get": {
                "description": "すべてのユーザーの入退室ログを取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "エントランス(入退室)管理"
                ],
                "summary": "アクセスログを取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "前回のログID（ページネーション用）",
                        "name": "last_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得するログの件数（デフォルト10）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "対象日（YYYY-MM-DD形式）",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.AccessLogResponse"
                            }
                        }
                    }
                }
            }
        },
        "/entrance/logs/{user_id}": {
            "get": {
                "description": "指定したユーザーの入退室ログを取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "エントランス(入退室)管理"
                ],
                "summary": "アクセスログをユーザー指定で取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "前回のログID（ページネーション用）",
                        "name": "last_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得するログの件数（デフォルト10）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.AccessLogResponse"
                            }
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "description": "存在する全ロールをまとめて取得",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ロール管理"
                ],
                "summary": "全ロール取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Role"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "全ユーザーの情報取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.UserResponse"
                            }
                        }
                    }
                }
            }
        },
        "/users/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "ユーザーを新規作成",
                "parameters": [
                    {
                        "description": "ユーザー情報",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UserResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "description": "指定したユーザーの情報を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "ユーザー情報取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "指定したユーザーを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "ユーザーを削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "指定したユーザーの情報を更新します（部分更新）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "ユーザー情報を更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新するユーザー情報（部分的に送信可能）",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}/roles": {
            "get": {
                "description": "指定したユーザーが持つロールを取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "指定ユーザーのロールを取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Role"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "指定したユーザーにロールを追加します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "指定ユーザーにロールを追加",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "追加するロールのID",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}/roles/{role_id}": {
            "delete": {
                "description": "指定したユーザーからロールを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ユーザー管理"
                ],
                "summary": "指定ユーザーのロールを削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ユーザーID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ロールID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AddRole": {
            "type": "object",
            "required": [
                "role_id"
            ],
            "properties": {
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "request.CreateUser": {
            "type": "object",
            "required": [
                "barcode",
                "name"
            ],
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "remaining_entries": {
                    "type": "integer"
                }
            }
        },
        "request.Entrance": {
            "type": "object",
            "required": [
                "barcode",
                "type"
            ],
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "entry",
                        "exit",
                        "auto"
                    ]
                }
            }
        },
        "request.UpdateUser": {
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "remaining_entries": {
                    "type": "integer"
                }
            }
        },
        "response.AccessLogResponse": {
            "type": "object",
            "properties": {
                "access_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "response.EntranceResponse": {
            "type": "object",
            "properties": {
                "access_type": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "response.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.UserResponse": {
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "registered_at": {
                    "type": "string"
                },
                "remaining_entries": {
                    "type": "integer"
                },
                "total_entries": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "JojiHouse Entrance System API",
	Description:      "JojiHouse の入退室管理システム API ドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
